### ISSUE TITLE
App authentication using tokens

### ISSUE THREAD

**Issue by tjacker** [zdurham/bcs-buddy#4]
Do we need to create a dual login system that uses the same BCS username, but separate passwords (current BCS password and new companion site password) to pass authentication to routes for CRUD operations?

**Comment by zdurham** [comment]
to avoid the shortness of tokens, we could create a second user (same username and password), but with a longer token refresh. Our auth middleware could refresh the api token whenever the api given token fails, so that our users dont have to continually log in every 20 or 30 minutes. I think this is the simplest way so users don't have to remember a second password.

**Comment by zdurham** [comment]
To clarify, we have session tokens specific to our application, with longer deprecation times than the API given tokens.
